2023-09-14 21:20:12.567 | ERROR    | handlers.user_handlers:greeting:23 - Message.reply() got an unexpected keyword argument 'photo_file'
Traceback (most recent call last):

  File "C:\Users\zhvit\YandexDisk\Python\Боты Telegram\@oxy_center_krd_bot\main.py", line 28, in <module>
    main()  # Запуск бота
    └ <function main at 0x0000020C9E4CC3A0>

  File "C:\Users\zhvit\YandexDisk\Python\Боты Telegram\@oxy_center_krd_bot\main.py", line 16, in main
    executor.start_polling(dp, skip_updates=True)
    │        │             └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000020C9E435A80>
    │        └ <function start_polling at 0x0000020C9E33AEF0>
    └ <module 'aiogram.utils.executor' from 'C:\\Users\\zhvit\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aio...

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\utils\executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x0000020C9E33B910>
    └ <aiogram.utils.executor.Executor object at 0x0000020C9E4BA0E0>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\utils\executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000020C9D3C9C60>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000020C9D31ACB0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000020C9D26E290>
    └ <Handle <TaskStepMethWrapper object at 0x0000020C9E4BBFA0>()>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x0000020C9E4BBFA0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x0000020C9E4BBFA0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x0000020C9E4BBFA0>()>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 63011656, "message": {"message_id": 195, "from": {"id": 535185511, "is_bot": false, "first_name": "𝖁𝖎𝖙...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000020C9E435A80>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x0000020C9E1E4D60>
                 │    │                │      └ <Update {"update_id": 63011656, "message": {"message_id": 195, "from": {"id": 535185511, "is_bot": false, "first_name": "𝖁𝖎𝖙𝖆...
                 │    │                └ <function Handler.notify at 0x0000020C9E266050>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x0000020C9E436B30>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000020C9E435A80>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {'state': <aiogram.dispatcher.storage.FSMContext object at 0x0000020C9E4BBFD0>}
                     │           │        └ (<Message {"message_id": 195, "from": {"id": 535185511, "is_bot": false, "first_name": "𝖁𝖎𝖙𝖆𝖑𝖎𝛄", "last_name": "𝖅𝖍𝖆𝖇𝖎𝖓𝖘𝖐𝖎𝛄", ...
                     │           └ <function greeting at 0x0000020C9E4896C0>
                     └ Handler.HandlerObj(handler=<function greeting at 0x0000020C9E4896C0>, spec=FullArgSpec(args=['message', 'state'], varargs=Non...

> File "C:\Users\zhvit\YandexDisk\Python\Боты Telegram\@oxy_center_krd_bot\handlers\user_handlers.py", line 21, in greeting
    await message.reply(message.from_user.id, photo_file=photo_file, caption=greeting_post, reply_markup=keyboards_greeting, parse_mode=types.ParseMode.HTML)
          │       │     │       │                        │                   │                           │                              │     │         └ <aiogram.utils.helper.Item object at 0x0000020C9E1A72E0>
          │       │     │       │                        │                   │                           │                              │     └ <class 'aiogram.types.message.ParseMode'>
          │       │     │       │                        │                   │                           │                              └ <module 'aiogram.types' from 'C:\\Users\\zhvit\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\typ...
          │       │     │       │                        │                   │                           └ <InlineKeyboardMarkup {"inline_keyboard": [[{"text": "🕵️ Задать анонимный вопрос", "callback_data": "ask_anonymous_question"}...
          │       │     │       │                        │                   └ '𝖁𝖎𝖙𝖆𝖑𝖎𝛄, Вас приветствует чат-бот клиники мужского и женского здоровья <b>OXY center!</b>'
          │       │     │       │                        └ <_io.BufferedReader name='media/photos/logo.jpg'>
          │       │     │       └ <aiogram.types.fields.Field object at 0x0000020C9E193580>
          │       │     └ <Message {"message_id": 195, "from": {"id": 535185511, "is_bot": false, "first_name": "𝖁𝖎𝖙𝖆𝖑𝖎𝛄", "last_name": "𝖅𝖍𝖆𝖇𝖎𝖓𝖘𝖐𝖎𝛄", "...
          │       └ <function Message.reply at 0x0000020C9E16F760>
          └ <Message {"message_id": 195, "from": {"id": 535185511, "is_bot": false, "first_name": "𝖁𝖎𝖙𝖆𝖑𝖎𝛄", "last_name": "𝖅𝖍𝖆𝖇𝖎𝖓𝖘𝖐𝖎𝛄", "...

TypeError: Message.reply() got an unexpected keyword argument 'photo_file'
2023-09-14 22:14:22.028 | ERROR    | handlers.sign_up_handlers:sign_up_handlers:16 - Inline keyboard button url '/start' is invalid: url host is empty
Traceback (most recent call last):

  File "C:\Users\zhvit\YandexDisk\Python\Боты Telegram\@oxy_center_krd_bot\main.py", line 30, in <module>
    main()  # Запуск бота
    └ <function main at 0x0000018167B50790>

  File "C:\Users\zhvit\YandexDisk\Python\Боты Telegram\@oxy_center_krd_bot\main.py", line 17, in main
    executor.start_polling(dp, skip_updates=True)
    │        │             └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000018167AB5C00>
    │        └ <function start_polling at 0x00000181679BAEF0>
    └ <module 'aiogram.utils.executor' from 'C:\\Users\\zhvit\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aio...

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\utils\executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x00000181679BB910>
    └ <aiogram.utils.executor.Executor object at 0x0000018167B3A590>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\utils\executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000018166AC9C60>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000018166A1ACB0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001816697E290>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 63011674, "callback_query": {"id": "2298604268772502787", "from": {"id": 535185511, "is_bot": false, "...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000018167AB5C00>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 │    │                       │      │      └ <aiogram.types.fields.Field object at 0x0000018167861150>
                 │    │                       │      └ <Update {"update_id": 63011674, "callback_query": {"id": "2298604268772502787", "from": {"id": 535185511, "is_bot": false, "f...
                 │    │                       └ <function Handler.notify at 0x00000181678F2050>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x0000018167B0C160>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000018167AB5C00>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<CallbackQuery {"id": "2298604268772502787", "from": {"id": 535185511, "is_bot": false, "first_name": "𝖁𝖎𝖙𝖆𝖑𝖎𝛄", "last_name"...
                     │           └ <function sign_up_handlers at 0x0000018167B09870>
                     └ Handler.HandlerObj(handler=<function sign_up_handlers at 0x0000018167B09870>, spec=FullArgSpec(args=['callback_query'], varar...

> File "C:\Users\zhvit\YandexDisk\Python\Боты Telegram\@oxy_center_krd_bot\handlers\sign_up_handlers.py", line 14, in sign_up_handlers
    await bot.send_message(callback_query.from_user.id, sign_up_text, reply_markup=keyboards_sign_up,  parse_mode=types.ParseMode.HTML, disable_web_page_preview=True)
          │   │            │              │             │                          │                              │     │         └ <aiogram.utils.helper.Item object at 0x0000018167827460>
          │   │            │              │             │                          │                              │     └ <class 'aiogram.types.message.ParseMode'>
          │   │            │              │             │                          │                              └ <module 'aiogram.types' from 'C:\\Users\\zhvit\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\typ...
          │   │            │              │             │                          └ <InlineKeyboardMarkup {"inline_keyboard": [[{"text": "Согласен", "callback_data": "agree"}, {"text": "Не согласен", "url": "/...
          │   │            │              │             └ 'Предлагаем нам с Вами познакомиться!\n\nИнформация о Ваших ФИО, городе и номере телефона нужны для оптимизации и персонализа...
          │   │            │              └ <aiogram.types.fields.Field object at 0x0000018167778B80>
          │   │            └ <CallbackQuery {"id": "2298604268772502787", "from": {"id": 535185511, "is_bot": false, "first_name": "𝖁𝖎𝖙𝖆𝖑𝖎𝛄", "last_name":...
          │   └ <function Bot.send_message at 0x00000181678A1AB0>
          └ <aiogram.bot.bot.Bot object at 0x0000018167AB5750>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\bot\bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
                   │    │       │   │       │             └ {'chat_id': 535185511, 'text': 'Предлагаем нам с Вами познакомиться!\n\nИнформация о Ваших ФИО, городе и номере телефона нужн...
                   │    │       │   │       └ <aiogram.utils.helper.Item object at 0x0000018167862E00>
                   │    │       │   └ <class 'aiogram.bot.api.Methods'>
                   │    │       └ <module 'aiogram.bot.api' from 'C:\\Users\\zhvit\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\b...
                   │    └ <function BaseBot.request at 0x00000181678A0310>
                   └ <aiogram.bot.bot.Bot object at 0x0000018167AB5750>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
                 │   │                  │    │              │    │       │             │       │     └ None
                 │   │                  │    │              │    │       │             │       └ {'chat_id': 535185511, 'text': 'Предлагаем нам с Вами познакомиться!\n\nИнформация о Ваших ФИО, городе и номере телефона нужн...
                 │   │                  │    │              │    │       │             └ 'sendMessage'
                 │   │                  │    │              │    │       └ <aiogram.bot.bot.Bot object at 0x0000018167AB5750>
                 │   │                  │    │              │    └ TelegramAPIServer(base='https://api.telegram.org/bot{token}/{method}', file='https://api.telegram.org/file/bot{token}/{path}')
                 │   │                  │    │              └ <aiogram.bot.bot.Bot object at 0x0000018167AB5750>
                 │   │                  │    └ <function BaseBot.get_session at 0x000001816787FB50>
                 │   │                  └ <aiogram.bot.bot.Bot object at 0x0000018167AB5750>
                 │   └ <function make_request at 0x000001816782BA30>
                 └ <module 'aiogram.bot.api' from 'C:\\Users\\zhvit\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\b...

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           │            │       │        │             │        │             │        └ <function ClientResponse.text at 0x0000018167360D30>
           │            │       │        │             │        │             └ <ClientResponse(https://api.telegram.org/bot6350767693:AAEercyVCWdBzuTX7FZGA4FJKqlVJU1rZqQ/sendMessage) [400 Bad Request]>
           │            │       │        │             │        │               <C...
           │            │       │        │             │        └ 400
           │            │       │        │             └ <ClientResponse(https://api.telegram.org/bot6350767693:AAEercyVCWdBzuTX7FZGA4FJKqlVJU1rZqQ/sendMessage) [400 Bad Request]>
           │            │       │        │               <C...
           │            │       │        └ <property object at 0x000001816720E750>
           │            │       └ <ClientResponse(https://api.telegram.org/bot6350767693:AAEercyVCWdBzuTX7FZGA4FJKqlVJU1rZqQ/sendMessage) [400 Bad Request]>
           │            │         <C...
           │            └ 'sendMessage'
           └ <function check_result at 0x000001816782B760>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
    │          │          │      └ "Bad Request: inline keyboard button URL '/start' is invalid: URL host is empty"
    │          │          └ <classmethod(<function _MatchErrorMixin.detect at 0x0000018167664D30>)>
    │          └ <class 'aiogram.utils.exceptions.BadRequest'>
    └ <module 'aiogram.utils.exceptions' from 'C:\\Users\\zhvit\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\a...

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
          │   │   │       └ "bad request: inline keyboard button url '/start' is invalid: url host is empty"
          │   │   └ None
          │   └ <class 'aiogram.utils.exceptions.BadRequest'>
          └ <class 'aiogram.utils.exceptions.URLHostIsEmpty'>

aiogram.utils.exceptions.URLHostIsEmpty: Inline keyboard button url '/start' is invalid: url host is empty
